### ISSUE TITLE
I18n (internationalization) support for the blog engine texts

### ISSUE THREAD

**Issue by ogourment** [xolvio/md-blog#14]
The blog engine should be able to display message and button texts in any language, not just English. (Note: for now, this does *not* refer to the blog posts themselves. Blog posts will not be internationalized)

The settings file probably is the right place for this directive:

```javascript
{
  "public": {
    "blog": {
      "locale" : 'fr' // or [ 'fr-CA', 'fr' ]
    }
  }
}
```

Implementation suggestion: use `tap:i18n`

**Comment by ogourment** [comment]
I'll be working on it in the next few days.

I have a few questions:
- is `tap:i18n` the right choice?
- how to specify the date formats for momentjs?
- any preference between sprintf and named variables?

**Comment by samhatoum** [comment]
Awesome! Thank you!

* Yes, `tap:i18n' looks great. I've not had any experience in i18n in Meteor yet and it looks like they're fully committed.
* We should probably extract [this settings object](https://github.com/xolvio/md-blog/blob/4817a43403056746cd377a46cc99e6e366ddc1cc/src/client/blog-client.js#L338) into the settings file. Should be easy
* What do you suggest?

**Comment by ogourment** [comment]
Closing. Works well for me.
