### ISSUE TITLE
I18n: serve blog depending on user/browser's preference

### ISSUE THREAD

**Issue by ogourment** [xolvio/md-blog#19]
Support multiple locales (right now moment js is configured for one locale in settings.json), and serve in the right one depending on the user's or browser's language.

**Comment by samhatoum** [comment]
Nice!

I was thinking the Moment config can be moved to the `<locale>.i18n.json` file, same with the app [name and description fields](https://github.com/xolvio/md-blog/blob/master/app/settings.json#L4)

**Comment by ogourment** [comment]
1. Moving the name and description fields: how do I test those? Where do they appear? There actually seems to be a little regression at this moment that the server's response: `<meta name="description" content="{{_ \"site_meta_desc\"}}">` Oops.
2. Browser's language is not available at the client side. This means we should extend the user object to add a locale field. I feel it's out of scope for a sample blog app. What would make sense, though, is to explain how to change the client's locale (ie. TAPi18n.setLanguage('<locale>') and changing the locale for `moment`)

**Comment by ogourment** [comment]
Here's the final commit!
1. I successfully tested `name` and was able to change the window title dynamically.
2. I explained in the README.md how to use the `Session` object to change the locale depending on the users' preferences.

Other small bug fixes.
Doc up to date.
Version now `0.4.0`

**Comment by samhatoum** [comment]
Thanks a million. I'll try to test when I have a moment and will release it all being well.

**Comment by ogourment** [comment]
Fixed!
