### ISSUE TITLE
METEOR_SETTINGS

### ISSUE THREAD

**Issue by bersling** [xolvio/md-blog#32]
Hi there!

When I try to install it, my page crashes with the following error:
```Error: --settings or METEOR_SETTINGS required.```

Does someone know what is the issue here?

**Comment by samhatoum** [comment]
this is normal, you need to supply a settings file with `meteor --settings settings.json`. Have a look at the readme

**Comment by Valentin-Seehausen** [comment]
But what is ogourment/settings for? Do I always have to start the app with meteor --settings settings.json? How does this work with meteor-deploy?

**Comment by Valentin-Seehausen** [comment]
Ah ok, sorry, I had to get the Meteor.settings right.

You can provide the settings as samhatoum mentioned for development and if you deploy with meteor-up, you can provide another settings in /mup. Now it should work. 

Actually I would appreciate a way, where you would not have to use the settings for the blog settings. I learned about Meteor.settings, but it took me one hour and I just wanted to include a blog.

**Comment by ogourment** [comment]
Good idea, I just need to implement [this](https://github.com/ogourment/settings/issues/3)
