### ISSUE TITLE
README needs clarifications

### ISSUE THREAD

**Issue by adamwong246** [xolvio/md-blog#36]
We ought to add to the instructions that you must explicitly add the `tap:i18n` package because it's NOT a dependency. I lost a few hours pulling my hair out over this.

**Comment by ogourment** [comment]
I guess you must have seen default, terse messages in the app? There might also have been warnings in the console saying `tap:i18n` was not initialized properly?
Anyway, sorry about that @adamwong246  `tap:i18n` is indeed a dependency in the package, but I'm not aware of a way to expose a whole package from package, only objects.
I've made the step explicit in the README.md.
