### ISSUE TITLE
Questions concerning customisation of icons through settings.json

### ISSUE THREAD

**Issue by thetechnaddict** [xolvio/md-blog#38]
I'm enjoying getting to know md-blog...

I'm integrating it into a site that uses materialise css 

I'd like to change the icons on the buttons - but as far as I can see I can only apply classes to the button element, not to the image element within a button of a particular id

Looking at the first button in blog-templates.html

     <button title="New" id="mdblog-new" class="{{mdBlogElementClasses 'button'}}">
           <i class="fa fa-pencil-square-o"></i>{{_ "new"}}</button>
      </section>

tells me that I can add a locator in the settings son file for 'button', but not for the icon:

Being naive I am wondering if changing the image element class to

    <i class="{{mdBlogElementClasses 'new-button-icon'}}"></i>

would allow me to then add the locator in prettify:

        {
            "locator": "button",
            "classes": ["btn-floating", "waves-effect", "waves-light"]
          },
          {
            "locator": "new-button-icon",
            "classes": ["mdi-content-add"]
          }

The buttons themselves I can colour style to match the site using the id selector, but it might be nice to use the class as elsewhere in Materialize

I'd also like to style the alerts, as these are another distinctive feature of the material style!

**Comment by samhatoum** [comment]
Glad to see you're using the styling features.

Have you tried setting a locator of: `button i`and setting classes to `["mdi-content-add"]`?

**Comment by thetechnaddict** [comment]
Hey thanks for the suggestion - 

No, that wasn't one I tried, but I have now and no it doesn't work - should it? Looking at the code I can't see how it would as the i element has the class hardcoded, unlike the buttons that are reactive - a UI.registerHelper sorts them out - as far as I can tell, although that helper is named to suggest it works on elements it could work on anything that has a suitable spacebar and corresponding entry in the settings file - so even though I am wishing to target the icons of specific types of buttons, I'm expecting it to work just fine.

I'll try dumping the code into a copy of my project and see if I can get it working - and if I can, I'll fork and offer it back - I was really asking if the approach stood a chance of success or if it was clearly doomed to failure - I am new to Meteor (sp please forgive me if my terminology is odd!)

Thanks again - I really like the approach.

**Comment by samhatoum** [comment]
No worries!

So [this line here](https://github.com/xolvio/md-blog/blob/master/src/client/blog-client.js#L215) should locate any element using the locator, and applies the classes

Perhaps there's a bug! I would love a reproduction repo or even better a PR :)

Let me know how you get on

**Comment by thetechnaddict** [comment]
I'm trying to work through this with a view to creating a pull request - but I am not at all used to Meteor, Meteor packages or even javaScript!

The only way I can think of working on the source is to create an app, place the source code into the app rather than adding the package - Please tell me if there is a better way.

When I do that I then come across a problem referencing Meteor.settings even if I run it using 

    $ meteor --settings settings.json

where settings.json is the settings file I have created for the packaged version.

**Comment by thetechnaddict** [comment]
OK - so the approach works but before I prepare a PR for you I'd like to check because, given that names are an indication of intention, this breaks your intention a little - it requires adding locators that are not elements so much as element+id

for instance

"button-icon-new"
"button-icon-delete"

so in the settings file we have:

        {
        "locator": "button-new",
        "classes": ["btn-floating", "btw-large", "teal",  "waves-effect", "waves-light"]
      },
      {
        "locator": "button-new-icon",
        "classes": ["mdi-content-add"]
      }

and in blog-templates.html we have

          <section class="blog-controls">
              <button title="New" id="mdblog-new" class="{{mdBlogElementClasses 'button-new'}}">
                  <i class="{{mdBlogElementClasses 'button-icon-new'}}"></i>{{_ "new"}}</button>
          </section>

If you are ok with that I'll work through the buttons and icons to make the configuration a little more fine-grained and hand it back as a PR

**Comment by thetechnaddict** [comment]
Looking at the range of changes that I'd really like to make in order to give it a meterial design, I'd really like to over-ride the templates, not just provide a layout and change some classes. 

Of course I want to have my cake and eat it - which is to say that I still want all the advantages of a package that is maintained and actively developed, whist being able to re-style at will.

aldeed/meteor-template-extension allows replacing a template (such as one in a package) with another whilst retaining the original templates helpers and events..

So the question - would you like me to implement the changes suggested above and provide a PR or should I just get on with replacing the templates in the package with my own using meteor-template-extension?

**Comment by thetechnaddict** [comment]
Ok - the overridable templates using nicolaslopezj/reactive-templates works really nicely

I'll continue to work through it on my local mashed together playground then I suppose I should fork, amend, create it as a package so that I can test it out and then make the PR?

If there is a better way please advise - else that is what I am doing.

Another adventure!

**Comment by thetechnaddict** [comment]
Brief update - perhaps necessary! Having convinced myself that it is very possible to override templates and easy to implement (I have it working) I am a little stuck with the process of creating a local package so that I can test and  ensure that the code I push to you is done and dusted.

**Comment by samhatoum** [comment]
hey @thetechnaddict thanks so much for looking into this. If you can come up with a solution for template overrides, I'd be happy to take it on.

Sorry I've been non responsive, it's been a busy stretch!

**Comment by thetechnaddict** [comment]
ha! I’ve just apologised for not acting fast enough.


the actual solution is sorted. reactive-tempates is sweet.


I’m struggling with local templates so that I can ensure I haven’t made typos (which I so do all the time) - also a really s**t week for me too!


then I’ll PR


No worries!

**Comment by thetechnaddict** [comment]
OK so I have it working as a local package with overridable templates - I'll move it across to the package file, modify the readme to explain how to override the templates

Do you need me to modify the app that is packaged up with it as well, or will you take that on?

**Comment by samhatoum** [comment]
so am I right in understanding that this is your workflow now:

clone this package into your local packages folder then override the templates that way?

**Comment by thetechnaddict** [comment]
No - that was just to be able to test the package.


You add the package as usual and override the templates in the app.


I forked your repo and have modified it to use reactive-templates and can make a push request - it is explained in the readme


I haven’t yet modified the app you include - if you are happy to do so yourself I can make the PR now.
