### ISSUE TITLE
Issues w/ Setup Accounts & Roles MD-BLOG

### ISSUE THREAD

**Issue by edavidzeron** [xolvio/md-blog#41]
Im having issues with step two (Setup Accounts & Roles) I followed the example but yet the package is still not working can you please figure out what I'm doing wrong 
```
Meteor.startup(function(){
    if(Meteor.users.find().count < 1){
        var users =[
            {
                "_id": "gKxmAP8Pweao5Dacn",
                "emails": [{ 
                "address":"zeke@gmail.com",
                "verified": false
            }],
                "profile":{"name" : "Zeke"},
                "roles":[mdblog-author]
            }]
        Roles.addUsersToRoles(user._id, ['mdblog-author']);
    }
});
```

**Comment by samhatoum** [comment]
are you running that on the server or client?

**Comment by edavidzeron** [comment]
Im running it on the server

**Comment by samhatoum** [comment]
looks like you're not creating the user, you're only defining the user. Try to do `Meteor.users.insert(users)`

**Comment by edavidzeron** [comment]
I did what you told me but now it says ReferenceError: Roles is not defined
    at app/server/server.js:13:9
here's my code below

Meteor.startup(function(){
    if(Meteor.users.insert){
        var users =[
            {
                "_id": "gKxmAP8Pweao5Dacn",
                "emails": [{ 
                "address":"zeke@gmail.com",
                "verified": false
            }],
                "profile":{"name" : "Zeke"},
                "roles":["mdblog-author"]
            }]
        Roles.addUsersToRoles(user._id, ['mdblog-author']);
    }
});

**Comment by samhatoum** [comment]
you need to install the Roles package. I recommend you download this repo and try this app locally

https://github.com/xolvio/md-blog/tree/master/app

Then see how you can modify it to suite your app

**Comment by edavidzeron** [comment]
Alright thanks for the help, I'll definitely do that

**Comment by samhatoum** [comment]
You're welcome :)
