### ISSUE TITLE
Using a storage other than AWS S3

### ISSUE THREAD

**Issue by thetechnaddict** [xolvio/md-blog#43]
Can I use a storage provider other than AWS S3 - using the same api but with different base_host and bucket url (and no regions)

I do realise that slingshot allows any number as plugins and I have found the instructions - but if i produce one (correctly that is!) how can I set md-blog to use it?

I'm not clear about the settings.json entries either - does it just infer what storage provider it is using from the directives provided or have I missed something?

**Comment by ogourment** [comment]
The `md-blog` package will use the directive you configured. See the sample `app`; it actually uses Google Cloud Storage. Just create a directive, give it a name, and put the name in the Settings: `public.blog.pictures.Slingshot.directive`. Try this please; it should be really straightforward.

**Comment by thetechnaddict** [comment]
Thanks for your answer - you have just made a penny drop!

I've found the slingshot.js file in the app - and it all makes sense - I think - I am too tired tonight to try it out.

from the instructions I had the impression that one set the directives in the settings file and looking through the package code I couldn't for the life of me join the dots (and nothing was working!)

Thanks so much.

**Comment by ogourment** [comment]
I checked the README and it's brief but should be enough information. If you have a better explanation, please submit a PR.
I'll close this one now.
